---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/wangyun1517/concourse-tutorial.git

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: hello-world
    file: resource-tutorial/01_task_hello_world/task_hello_world.yml
